alias la='ls -ahF'
alias ll='ls -lhFt'
alias ltr='tree -L 1'

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad

if [[ -s ~/.rvm/scripts/rvm ]]; then source ~/.rvm/scripts/rvm ; fi

if [[ -s ~/.private-profile ]] ; then source ~/.private-profile ; fi

export EDITOR="vim"

mkdir -p $HOME/go/{bin,pkg,src}
export GOPATH=$HOME/go
export GOROOT=/usr/local/Cellar/go/HEAD
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

. /usr/local/opt/asdf/asdf.sh
